controller_list:
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - base_joint_gripper_left
      - base_joint_gripper_right
initial:  # Define initial robot poses.
  - group: gripper
    pose: close